const ClassStats = {
    Fighter: {
      Strength: 15,
      Vigor: 15,
      Agility: 15,
      Dexterity: 15,
      Will: 15,
      Knowledge: 15,
      Resourcefulness: 15,
      Health: 110,
    },
    Barbarian: {
      Strength: 25,
      Vigor: 25,
      Agility: 13,
      Dexterity: 12,
      Will: 18,
      Knowledge: 5,
      Resourcefulness: 7,
      Health: 130,
    },
    Rogue: {
      Strength: 9,
      Vigor: 10,
      Agility: 21,
      Dexterity: 25,
      Will: 10,
      Knowledge: 10,
      Resourcefulness: 20,
      Health: 99.5,
    },
    Ranger: {
      Strength: 12,
      Vigor: 10,
      Agility: 20,
      Dexterity: 18,
      Will: 10,
      Knowledge: 12,
      Resourcefulness: 23,
      Health: 101,
    },
    Wizard: {
      Strength: 6,
      Vigor: 7,
      Agility: 15,
      Dexterity: 17,
      Will: 20,
      Knowledge: 25,
      Resourcefulness: 15,
      Health: 93.5,
      Memory: 19,
    },
    Cleric: {
      Strength: 11,
      Vigor: 13,
      Agility: 12,
      Dexterity: 14,
      Will: 23,
      Knowledge: 20,
      Resourcefulness: 12,
      Health: 105,
      Memory: 14,
    },
    Bard: {
      Strength: 13,
      Vigor: 13,
      Agility: 13,
      Dexterity: 20,
      Will: 11,
      Knowledge: 20,
      Resourcefulness: 15,
      Health: 106,
      Memory: 14,
    },
    Warlock: {
      Strength: 11,
      Vigor: 14,
      Agility: 14,
      Dexterity: 15,
      Will: 22,
      Knowledge: 15,
      Resourcefulness: 14,
      Health: 106.5,
      Memory: 9,
    },
    Druid: {
      Strength: 12,
      Vigor: 13,
      Agility: 12,
      Dexterity: 12,
      Will: 18,
      Knowledge: 20,
      Resourcefulness: 18,
      Health: 105.5,
      Memory: 14,
    },
    Sorcerer: {
      Strength: 10,
      Vigor: 10,
      Agility: 10,
      Dexterity: 18,
      Will: 25,
      Knowledge: 20,
      Resourcefulness: 12,
      Health: 100,
      Memory: 14,
    },
  };
  
  export default ClassStats;
  